### ISSUE TITLE
Instructions don't work

### ISSUE THREAD

**Issue by scoopgracie** [apertium/apertium-eng-spa#15]
It says to run `./configure`. This file does not exist.

**Comment by scoopgracie** [comment]
You need to run ./autogen.sh first. Will submit a PR.

**Comment by mr-martian** [comment]
@scoopgracie `configure` is created by running `autoreconf -fvi`. `autogen.sh` is little more than a wrapper around `autoreconf -fi && ./configure`.

I suppose this is essentially a variant of apertium/apertium-init#74
