### ISSUE TITLE
eng tagger bugs

### ISSUE THREAD

**Issue by vivekvardhanadepu** [apertium/apertium-eng-spa#18]
- eng tagger is tagging `$some_number` as `^$ ^some_number<num>$`
**input**: `AIDS treatments that may cost $18 000 per annum for one person are obviously not affordable by countries whose annual health budget may be less than $5 per capita`
**output**: `^AIDS<n><acr><sg>$ ^treatment<n><pl>$ ^that<cnjsub>$ ^may<vaux><inf>$ ^cost<vblex><inf>$ ^$ ^18<num>$ ^000<num>$ ^per<pr>$ ^*annum$ ^for<pr>$ ^one<num><sg>$ ^person<n><sg>$ ^be<vbser><pres>$ ^obviously<adv>$ ^not<adv>$ ^affordable<adj>$ ^by<pr>$ ^country<n><pl>$ ^whose<rel><aa><mf><sp>$ ^annual<adj>$ ^health<n><sg>$ ^budget<n><sg>$ ^may<vaux><inf>$ ^be<vbser><inf>$ ^less~than<pr>$ ^$ ^5<num>$ ^per~capita<adj>$ ^.<sent>$`
- Also, it is considering `IT` as pronoun
**input**: `system of electronic employment cards and using suitable IT systems to monitor all these policies.`
**output**: `^system<n><sg>$ ^of<pr>$ ^electronic<adj>$ ^employment<n><sg>$ ^card<n><pl>$ ^and<cnjcoo>$ ^use<vblex><ger>$ ^suitable<adj>$ ^prpers<prn><subj><p3><nt><sg>$ ^system<n><pl>$ ^to<pr>$ ^monitor<vblex><inf>$ ^all<predet><sp>$ ^this<det><dem><pl>$ ^policy<n><pl>$ ^.<sent>$ `

**Comment by xavivars** [comment]
Haven't checked myself, but I have a couple of questions:
- are you escaping the input? That may explain the "empty" analysis created for $
- is IT a word in the dictionary? If it's not, that would explain it as well...

**Comment by mr-martian** [comment]
```
daniel@computer-name-here:~$ echo "IT" | apertium eng-morph
^IT/IT<n><acr><sg>/prpers<prn><subj><p3><nt><sg>/prpers<prn><obj><p3><nt><sg>$^./.<sent>$
daniel@computer-name-here:~$ echo "IT" | apertium -d apertium-data/apertium-eng-spa/ eng-spa-anmor
^IT/PRPERS<prn><subj><p3><nt><sg>/PRPERS<prn><obj><p3><nt><sg>$^./.<sent>$
```
Yep, `IT` as an acronym isn't in the bilingual dictionary.

```
daniel@computer-name-here:~$ echo "$" | apertium -d apertium-data/apertium-eng-spa/ eng-spa-anmor
^$/$<mon>$^./.<sent>$
daniel@computer-name-here:~$ echo '$3' | apertium -d apertium-data/apertium-eng/ eng-morph
$^3/3<num>$^./.<sent>$
daniel@computer-name-here:~$ echo '$3' | apertium -d apertium-data/apertium-eng-spa/ eng-spa-anmor
^$/$<mon>$^3/3<num>$^./.<sent>$
daniel@computer-name-here:~$ echo '$3' | apertium -d apertium-data/apertium-eng-spa/ eng-spa-tagger
^$<mon>$^3<num>$^.<sent>$
```
Looks like an escaping bug somewhere in the pipeline - I'll see if I can make sense of why `eng-morph` is different in a couple hours.

**Comment by vivekvardhanadepu** [comment]
> Haven't checked myself, but I have a couple of questions:
> 
>     * are you escaping the input? That may explain the "empty" analysis created for $
No

**Comment by mr-martian** [comment]
The differing behavior of `eng-morph` is irrelevant because I didn't realize that this repo hasn't been monolingualized yet (#6).

As for the escaping issue, my explanation in #19 applies here too.
