### ISSUE TITLE
Brackets '[' and ']' translation bug

### ISSUE THREAD

**Issue by vivekvardhanadepu** [apertium/apertium-eng-spa#19]
`lt-proc -b spa-eng.autobil.bin` 
on 
`^común<adj><mf><sg>$ ^[<lpar>$ ^*COM$ ^(<lpar>$ ^2002<num>$ ^)<rpar>$ ^186<num>$ ^?<sent>$ 
^*C5$ ^-<guio>$ ^0331<num>$ ^2002<num>$ ^-<guio>$ ^2002<num>$ ^2175<num>$ ^(<lpar>$ ^*COS$ ^)<rpar>$ ^]<rpar>$ ^.<sent>$` 
gives me
 ` ^común<adj><mf><sg>/common<adj><sg>$ [<lpar>$ ^*COM$ ^(<lpar>$ ^2002<num>$ ^)<rpar>$ ^186<num>$ ^?<sent>$ 
^*C5$ ^-<guio>$ ^0331<num>$ ^2002<num>$ ^-<guio>$ ^2002<num>$ ^2175<num>$ ^(<lpar>$ ^*COS$ ^)<rpar>$ ^]^<rpar>/@<rpar>$ ^.<sent>/.<sent>$ `

**Comment by mr-martian** [comment]
Square brackets need to be escaped. Use `^\[<lpar>$ ^\]<rpar>` rather than `^[<lpar> ^]<rpar>`.

**Comment by vivekvardhanadepu** [comment]
> Square brackets need to be escaped. Use `^\[<lpar>$ ^\]<rpar>` rather than `^[<lpar> ^]<rpar>`.

That's tagger output

**Comment by mr-martian** [comment]
Running text through `apertium eng-spa-tagger` includes `apertium-retxt` which removes character escapes, after which point it isn't safe to pass the result directly to other pipeline modules:

```
daniel@computer-name-here:~/apertium-data/apertium-eng-spa$ echo '[33]' | apertium -d . eng-spa-tagger
^[<lpar>$^33<num>$^]<rpar>$^.<sent>$
daniel@computer-name-here:~/apertium-data/apertium-eng-spa$ echo '[33]' | apertium-destxt | lt-proc eng-spa.automorf.bin | apertium-tagger -g eng-spa.prob | apertium-retxt 
^[<lpar>$^33<num>$^]<rpar>$^.<sent>$
daniel@computer-name-here:~/apertium-data/apertium-eng-spa$ echo '[33]' | apertium-destxt | lt-proc eng-spa.automorf.bin | apertium-tagger -g eng-spa.prob
^\[<lpar>$^33<num>$^\]<rpar>$^.<sent>$[][
]
```

Probably what you want to do is pass your corpus through `apertium-destxt` manually and then run `apertium` with the option `-f none` to disable format mangling.
