### ISSUE TITLE
_US no longer works

### ISSUE THREAD

**Issue by bentley** [apertium/apertium-eng-spa#8]
Moving to three‐letter codes results in the US variant translation not working.

Comparing git master built from “make dist” to apertium-en-es-0.8.0:

    $ echo 'Los colores' | apertium es-en   
    The colours
    $ echo 'Los colores' | apertium es-en_US
    The colors
    $ echo 'Los colores' | apertium spa-eng   
    The colours
    $ echo 'Los colores' | apertium spa-eng_US
    USAGE: apertium-transfer trules preproc biltrans [input [output]]
           apertium-transfer -b trules preproc [input [output]]
           apertium-transfer -n trules preproc [input [output]]
           apertium-transfer -x extended trules preproc biltrans [input [output]]
           apertium-transfer -c trules preproc biltrans [input [output]]
           apertium-transfer -t trules preproc biltrans [input [output]]
      trules     transfer rules file
      preproc    result of preprocess trules file
      biltrans   bilingual letter transducer file
      input      input file, standard input by default
      output     output file, standard output by default
      -b         input from lexical transfer
      -n         don't use bilingual dictionary
      -x bindix  extended mode with user dictionary
      -c         case-sensitiveness while accessing bilingual dictionary
      -t         trace (show rule numbers and patterns matched)
      -T         trace, for apertium-transfer-tools (also sets -t)
      -z         null-flushing output on '
      -h         shows this message

**Comment by ftyers** [comment]
Hmm, this is weird, but should be fixed in 1db4fe7, I don't know how that happened :)
